name: fleeque
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5

  cupertino_icons: ^1.0.2
  core_ui:
    path: core_UI
  core:
    path: core
  data:
    path: data
  domain:
    path: domain
  app_bar:
    path: features/app_bar
  welcome:
    path: features/welcome
  carousel:
    path: features/carousel
  authentification:
    path: features/authentification
  firebase_auth: ^4.8.0
  cloud_firestore: ^4.9.0
  get_it: ^7.6.0
  intl: ^0.18.1
  flutter_bloc: ^8.1.3
  google_sign_in: ^6.1.5
  firebase_core: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  google_fonts: ^5.1.0
  carousel_slider: ^4.2.1
  dots_indicator: ^2.1.1
  flutter_native_splash: ^2.3.2
  

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
flutter_native_splash:
  color: '#000000'
  image_ios: assets/images/splash_logo_ios.png
  image_android: assets/images/splash_logo_android.png

  android_12:
    image: assets/images/splash_logo_android12.png
    color: '#000000'

  android: true
  ios: true