name: fleeque
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  core_ui:
    path: core_UI/core_ui
  core:
    path: core/core
  app_bar:
    path: features/app_bar
  login:
    path: features/login
  welcome:
    path: features/welcome
  carousel:
    path: features/carousel

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  google_fonts: ^5.1.0
  carousel_slider: ^4.2.1
  dots_indicator: ^2.1.1
  flutter_native_splash: ^2.3.2

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
